# Generated by Django 3.2.7 on 2021-09-13 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=15)),
                ('body', models.CharField(max_length=100)),
                ('answer', models.CharField(blank=True, default='', max_length=100)),
                ('countReported', models.IntegerField(default=0)),
                ('isPinned', models.BooleanField(default=False)),
                ('isVisible', models.BooleanField(default=True)),
                ('toUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
    ]
